image:
  file: .gitpod.Dockerfile
tasks:
  - init: go install && gosh
vscode:
  extensions:
    - kosz78.nim@0.6.4:J4mmxMK624S+XisrptVQ/Q==
    - ms-vscode.cpptools@0.26.2-insiders:ZfaNmwBAkeWyphIu+nLlww==
