image:
  file: .gitpod.Dockerfile
tasks:
  - init: go get -v -t -d ./... && go install && bash webapp.sh
ports:
  - port: 8080
    onOpen: ignore
vscode:
  extensions:
    - kosz78.nim@0.6.4:J4mmxMK624S+XisrptVQ/Q==
    - ms-vscode.cpptools@0.26.2-insiders:ZfaNmwBAkeWyphIu+nLlww==
