name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: sudo curl -s "https://raw.githubusercontent.com/JesterOrNot/gosh/master/build" | sh
    - name: try Makefile
      run: sudo make install_deps setup
