name: Test oneline curl script

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line install script
      run: curl -s "https://raw.githubusercontent.com/JesterOrNot/gosh/master/build" | sh \
           && gosh
      
