name: Docker Image CI

on: [push]

jobs:

  build:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Gitpod image
      run: docker build . --file .gitpod.Dockerfile --tag gitpod-image:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag official-image:$(date +%s)
