name: Gitpod Image CI

on: [push]

jobs:

  build:
    name: Build Gitpod images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Gitpod image
      run: docker build . --file .gitpod.Dockerfile --tag gitpod-image:$(date +%s)
