name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to to gosh and thank-you for your interest!!'' first issue'
        pr-message: 'Welcome to to gosh and thank-you for your interest!! remember to add comments to your code!'' first pr'
