name: test-setup-script

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: sudo curl https://raw.githubusercontent.com/JesterOrNot/gosh/master/setup.sh | bash
